apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: __name__
spec:
  inputs:
    # params:
    resources:
    - name: workspace
      type: git
      targetPath: target-workspace
  outputs:
    resources:
    - name: build-sources
      type: ubuntu
  steps:
    - name: build-sources
      image: __image__
      command: 
      - /bin/bash
      args: 
      - ['-c', 'echo hello world']