apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: $(name)
spec:
  inputs:
    # params:
    resources:
    - name: workspace
      type: git
      targetPath: target-workspace
  outputs:
    resources:
    - name: build-sources
      type: ubuntu
  steps:
    - name: build-sources
      image: $(image)
      command: 
      - /bin/bash
      args: 
      - ['-c', 'echo $(image) world']